### ISSUE TITLE
Help with understanding: Why does "prove" work in this way?

### ISSUE THREAD

**Issue by bemeyert** [ingydotnet/test-more-bash#3]
Hi @ingydotnet ,

This might be the wrong place to ask this question. Sry about this.

Why does `prove` or better `App::Prove` work this way? I'm just trying to comprehend this. And how can I understand this part from the Description: "For the most part it should work exactly the same."

BTW: I think that `test-more-bash` is awesome and much "friendlier" than for example bats.

Cheers

**Comment by ingydotnet** [comment]
From the doc: Prove knows it's Bash from the first line (the hashbang), and it just works.

`prove` runs a program/script in any language and then captures the output. It analyzes the output and gives a report.

'For the most part' means that prove has options that are only for Perl, since it was originally made for Perl. Realizing that it would work for just about any language, came later.

Hope that helps.

**Comment by bemeyert** [comment]
Thanks for your helpful answer. I already "supected" that `prove` is doing something like that. I'm still trying to find the corresponding piece of code ;) Something for the evening.
Cheers

**Comment by bemeyert** [comment]
Srry, forgot to close this one.
